### ISSUE TITLE
Communicating between Xposed and Classes like Activity or Service

### ISSUE THREAD

**Issue by BenjaminFaal** [rovo89/XposedInstaller#245]
Hello,

Is there any function the call a method from an Activity or a Service.

Or at least a good way to share data between an Xposed module and other classes.

Kind regards,

Benjamin

**Comment by simonbuehler** [comment]
hi,
sorry for jumping in on this so late, but this seems to be the only source where my exact problem is described:

i have a `ButtonService` which handles OnClickListeners and should be the single class where the data and logic to calculate the Location is kept,

`ButtonService`  sends a broadcast to update the listeners, one of them is the module with the hooks.I use `RemotePreferences` in the module to read data altered in the  `ButtonService`, so far so good and working.

Now there is also another hooked method that requests a new location which should be calculated in the  `ButtonService` 

so mostly the data flow is
 `ButtonService`  -> broadcast --> `xposed module` (and others)

but whats best practice to implement

`xposed beforehooked method -> call Buttonservice.calculateNewLoc() -> continue beforehooked Method `?

**Comment by simonbuehler** [comment]
@theknut please give me some hints, much appreciated!!

**Comment by theknut** [comment]
I don't know man. I guess you can't do it that way because your code would have to wait until you get the new intent in order to continue. So your code won't run asynchronously and you might get performance issues or even freezes in cases of errors.

You might be able to call your calculateNewLoc method, exit the hooked method (set result null) and then call your calculateNewLoc method again after you received the new intent. You might have to send a few intents back and forth before actually be able to continue your hooked method.

Keine Ahnung was du machen willst, aber evtl. musst du einfach einen anderen Weg finden, um an deine Daten zu kommen. Drei, vier Intents hin und her zuschicken bevor die gehookte Methode ausgeführt werden kann klingt nicht gerade performant. Überleg mal, ob du das noch irgendwie anders regeln kannst. Viel Erfolg!

**Comment by simonbuehler** [comment]
thanks for the comment, at least i know now that i didn't miss something obvious here!
