### ISSUE TITLE
Configurable repo refresh interval

### ISSUE THREAD

**Issue by pylerSM** [rovo89/XposedInstaller#258]
ATM interval is hard coded to one day - https://github.com/rovo89/XposedInstaller/blob/master/src/de/robv/android/xposed/installer/util/RepoLoader.java#L47.

I would like make it configurable. do you - @rovo89 - agree or not? I think I could implement it but I need your opinion.

**Comment by theknut** [comment]
Come on man. Let the man do his work. What the heck. We freaking need
Xposed on L rather than a stupid configurable interval count. Nobody
fucking cares about the installer (sorry rovo). We rather need the
framework to work. Just my two cents man, but I'm hoping every day I open
reddit there is a post about Xposed. All those requests and improvements
are just keeping him from working on whats most important.

I may sound like an asshole and maybe I am but I really want this to work
on L. I was patient the whole time and never asked rovo about L support.
I'm just silently waiting for it and seeing each and every of this Github
notifications make me really upset.

I'm sorry man, I really appreciate your work and your work for my module
but for the love of God, let the man concentrate on other things. The
installer is working just fine for 99,99% of the users.

2015-01-15 19:24 GMT+01:00 pyler <notifications@github.com>:

**Comment by pylerSM** [comment]
Wow. Just wow.

I am sorry for "contributing" features and fixes.. :/ and *wasting* rovo89's time.

**Comment by theknut** [comment]
You didn't get my point. I basically said you are trying to make something
which is already perfect even more perfect. Which is completely fine but
right now the priority is clearly not on the installer because the
installer is not "broken".

You heard him saying he can't work on it very often. So I rather want him
to concentrate what's more important.
Am 15.01.2015 21:18 schrieb "pyler" <notifications@github.com>:

**Comment by pylerSM** [comment]
So close this "open source" project and we are done. No issues, no PRs, simply nothing what would waste his time.

**Comment by GermainZ** [comment]
In which way would this be configurable? If it would allow values less than a day, then I think rovo's previous stance regarding bandwidth remains unchanged.

If it allows longer intervals, I'm not sure it would be useful since the check only happens when you open the installer anyway. I'm just curious if there's a use case that doesn't bring up the same issues as previous suggestions.

**Comment by pylerSM** [comment]
Well, Xposed download server is provided by XDA now so rovo89 should tell new statement.

Also, "disable (refresh interval)" could be on of options.

**Comment by rovo89** [comment]
Repo XML is still served by my server as there's quite a difference between pushing unchangeable files (APKs) and the XML that changes several times per day, has to be in sync with the partial XMLs and should be updated as soon as a module is saved.

So in short: Veto from my side to make this less than a day, at least for the next months.

**Comment by pylerSM** [comment]
Many people want to send you some money so they could be used for better server. But OK, I understand, suggestion is bad so I will close this.
