### ISSUE TITLE
Actual modules are not the same with the modules in UI

### ISSUE THREAD

**Issue by liudongmiao** [rovo89/XposedInstaller#300]
As I know, the modules list used by `xposed` is `modules.list`, but the modules list used by `Xposed Installer` is SharedPreferences `enabled_modules`. Most of time, there are the same, but they are not always same.

For example, when the module updated, `Xposed Installer` cannot receive the `android.intent.action.PACKAGE_CHANGED` broadcast, so the `modules.list` is not updated, then it's not enaboed after reboot, but it's enalbed in the `Xposed Installer`'s UI. (There are many possiblity to prevent Xposed Installer to receive the broadcast: user force stopped the Xposed Installer, some modified system prevent Xposed Installer to receive broadcast, and some xposed modules do so too.)

Another another possiblity: If the system cannot boot, user delete the `modules.list`, but the UI shows the module is enabled while actually the module is not enabled at all.

Here I'm asking for your idea. If you think it's a problem, I will add a pull request to fix this by only using the `modules.list`. If you don't think it's a problem, I will create a module to hook `Xposed Installer` only use `modules.list`.

**Comment by pylerSM** [comment]
Yes, two files to store activated modules is not a good solution IMHO. If you know how to fix, upload your fix.

**Comment by rovo89** [comment]
Well, the preferences store the module package names, while `modules.list` stores the file names, so they *are* different purposes.

About the situations you mentioned:

1. Force stop: Could only be solved if only the package name was saved, but when Zygote is started, the package manager service doesn't exist to turn it into the file name. Could only be fixed by reading the package.xml manually, which is too much effort and too unstable.
2. Somebody modified the system: I can't fix stupid users who intentionally break the app.
3. Modules/apps modify the file: They shouldn't. Not my problem.
4. User deleted the file: Not the best idea, they should rather create the file to disable Xposed.

The only situations I'm willing to look at are 1 and maybe 4. None of these can be fixed by using a single file, so I see no necessity for your pull request, it only fixes situation 3.

Actually, it makes the situation even worse: Getting from the package name to the file name at runtime is trivial, but the other way around is unreliable. `getPackageArchiveInfo()` requires actually parsing all the files again. It will fail if the filename has changed. So when a module has been updated, but wasn't noticed by the installer, it will still have the old filename (e.g. `com.example-1.apk`) and won't be able to read the package name from that. Then the module wouldn't be shown as active anymore if one update was missed by the receiver. However, if another update is done (which is missed again), the first suffix will be used again, so suddenly the module becomes active again. That's why it's better to remember the package name.

It would be ok from my point of view to write the modules list again when starting the app. This would ensure for situations 1 and 4 that the files match.

**Comment by liudongmiao** [comment]
The main problem is the module is not actually loaded, but the UI displays it as enabled.
So I think, it's necessary to make the UI displays actual active modules.
And whatever solution will be good. So I was asing for your idea.

Actually, I'd like to use following codes to get the package name from apk file. It's very quick, often less than 10ms.
```java
// following using some hide method
AssetManager asset = new AssetManager();
int cookie = asset.addAssetPath(apkPath);
XmlResourceParser parser = asset.openXmlResourceParser(cookie, "AndroidManifest.xml");
String packageName = null;
while (true) {
    int type = parser.next();
    if (type == XmlPullParser.END_DOCUMENT) { // end
        break;
    } else if (type == XmlPullParser.START_TAG) {
        // I don't think it's nesseraty to check the tag name, which should be "manifest"
        packageName = parser.getAttributeValue(null, "package");
    }
}
```
