### ISSUE TITLE
Trying to Install the new Beta

### ISSUE THREAD

**Issue by thehappydinoa** [rovo89/XposedInstaller#417]
I was trying to install the new beta and got a error 404

**Comment by thehappydinoa** [comment]
Then I tried installing the zip through TWRP got
```
I:Setting active slot A
RECOVERY_SDCARD_ON_DATA := true
I:Lun file '/sys/class/android_usb/android0/f_mass_storage/lun0/file' does not exist, USB storage mode disabled
TW_INCLUDE_CRYPTO := true
I:Find_File: Error opening '/sys/class/backlight'
I:Found brightness file at '/sys/class/leds/lcd-backlight/brightness'
I:TWFunc::Set_Brightness: Setting brightness control to 149
I:LANG: en
I:AB_OTA_UPDATER := true
I:[MTP] MtpServer::run fd: 28
sideload-host file size 8055074 block size 65536
Installing zip file '/sideload/package.zip'
I:Update binary zip
I:Zip does not contain SELinux file_contexts file in its root.
I:has_legacy_properties: Found legacy property match!
I:Legacy property environment initialized.
******************************
Xposed framework installer zip
******************************
- Mounting /system and /vendor read-write
! Failed: /system could not be mounted!
Updater process ended with ERROR: 1
I:Legacy property environment disabled.
I:Install took 1 second(s).
I:Signaling child sideload process to exit.
I:Waiting for child sideload process to exit.
sideload_host finished
E:[MTP] request read returned -1, errno: 5, exiting MtpServer::run loop
Done.
Done processing script file
```

**Comment by roblee78** [comment]
Short circuit it please repeat

**Comment by roblee78** [comment]
Short circuit it please repeat


On Jan 8, 2018 6:08 PM, "Aidan Holland" <notifications@github.com> wrote:

Then I tried installing the zip through TWRP got

I:Setting active slot A
RECOVERY_SDCARD_ON_DATA := true
I:Lun file '/sys/class/android_usb/android0/f_mass_storage/lun0/file'
does not exist, USB storage mode disabled
TW_INCLUDE_CRYPTO := true
I:Find_File: Error opening '/sys/class/backlight'
I:Found brightness file at '/sys/class/leds/lcd-backlight/brightness'
I:TWFunc::Set_Brightness: Setting brightness control to 149
I:LANG: en
I:AB_OTA_UPDATER := true
I:[MTP] MtpServer::run fd: 28
sideload-host file size 8055074 block size 65536
Installing zip file '/sideload/package.zip'
I:Update binary zip
I:Zip does not contain SELinux file_contexts file in its root.
I:has_legacy_properties: Found legacy property match!
I:Legacy property environment initialized.
******************************
Xposed framework installer zip
******************************
- Mounting /system and /vendor read-write
! Failed: /system could not be mounted!
Updater process ended with ERROR: 1
I:Legacy property environment disabled.
I:Install took 1 second(s).
I:Signaling child sideload process to exit.
I:Waiting for child sideload process to exit.
sideload_host finished
E:[MTP] request read returned -1, errno: 5, exiting MtpServer::run loop
Done.
Done processing script file

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rovo89/XposedInstaller/issues/417#issuecomment-356137333>,
or mute the thread

**Comment by rovo89** [comment]
Which device? On Pixel phones, /system isn't available as expected in TWRP. Try installing via the app please.

**Comment by thehappydinoa** [comment]
I tried installing through the app and it gave me a error 404 for the installer, but I could download the uninstaller. I am running 8.0.0 on an Essential Phone

**Comment by rovo89** [comment]
Confirmed. I fixed the JSON now, please try again.

**Comment by thehappydinoa** [comment]
Thank you very much.

**Comment by rovo89** [comment]
Can you use Xposed now or is there still a problem?

**Comment by thehappydinoa** [comment]
I could download it but I had to use the Magisk module

**Comment by rovo89** [comment]
v90-beta2 should now be installable via TWRP, even for Pixel devices.
